<<<<<<< HEAD
2017-09-19 09:59:21,061 [INFO] from application in scala-execution-context-global-61 - Creating Pool for datasource 'default'
2017-09-19 09:59:21,419 [INFO] from play.api.db.DefaultDBApi in scala-execution-context-global-61 - Database [default] connected at jdbc:mysql://localhost:3306/eatalotdb
2017-09-19 09:59:22,519 [INFO] from application in scala-execution-context-global-61 - ApplicationTimer demo: Starting application at 2017-09-19T07:59:22.518Z
2017-09-19 09:59:23,586 [WARN] from org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator in scala-execution-context-global-61 - HV000184: ParameterMessageInterpolator has been chosen, EL interpolation will not be supported
2017-09-19 09:59:24,245 [INFO] from play.api.http.EnabledFilters in scala-execution-context-global-61 - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.csrf.CSRFFilter
    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter
    filters.ExampleFilter

2017-09-19 09:59:24,258 [INFO] from play.api.Play in scala-execution-context-global-61 - Application started (Dev)
2017-09-19 10:00:42,390 [WARN] from play in application-akka.actor.default-dispatcher-3 - You are using status code '200' with flashing, which should only be used with a redirect status!
=======
2017-10-17 18:17:10,326 [INFO] from application in scala-execution-context-global-63 - Creating Pool for datasource 'default'
2017-10-17 18:17:15,973 [INFO] from play.api.db.DefaultDBApi in scala-execution-context-global-63 - Database [default] connected at jdbc:mysql://212.24.98.135:3306/eatalotdb?verifyServerCertificate=false&useSSL=true
2017-10-17 18:17:22,055 [WARN] from org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator in scala-execution-context-global-63 - HV000184: ParameterMessageInterpolator has been chosen, EL interpolation will not be supported
2017-10-17 18:17:22,438 [INFO] from play.api.Play in scala-execution-context-global-63 - Application started (Dev)
2017-10-17 18:37:41,637 [WARN] from com.zaxxer.hikari.pool.PoolBase in application-akka.actor.default-dispatcher-9 - HikariPool-1 - Failed to validate connection com.mysql.jdbc.JDBC4Connection@4ad18a4d (No operations allowed after connection closed.)
2017-10-17 18:37:46,650 [WARN] from com.zaxxer.hikari.pool.PoolBase in application-akka.actor.default-dispatcher-9 - HikariPool-1 - Failed to validate connection com.mysql.jdbc.JDBC4Connection@25e715fd (No operations allowed after connection closed.)
2017-10-17 18:37:51,656 [WARN] from com.zaxxer.hikari.pool.PoolBase in application-akka.actor.default-dispatcher-9 - HikariPool-1 - Failed to validate connection com.mysql.jdbc.JDBC4Connection@d04df24 (No operations allowed after connection closed.)
2017-10-17 18:37:56,663 [WARN] from com.zaxxer.hikari.pool.PoolBase in application-akka.actor.default-dispatcher-9 - HikariPool-1 - Failed to validate connection com.mysql.jdbc.JDBC4Connection@c5d8042 (No operations allowed after connection closed.)
2017-10-17 18:38:01,665 [WARN] from com.zaxxer.hikari.pool.PoolBase in application-akka.actor.default-dispatcher-9 - HikariPool-1 - Failed to validate connection com.mysql.jdbc.JDBC4Connection@57de296d (No operations allowed after connection closed.)
2017-10-17 18:38:06,672 [WARN] from com.zaxxer.hikari.pool.PoolBase in application-akka.actor.default-dispatcher-9 - HikariPool-1 - Failed to validate connection com.mysql.jdbc.JDBC4Connection@678270ef (No operations allowed after connection closed.)
2017-10-17 18:38:06,755 [ERROR] from application in application-akka.actor.default-dispatcher-9 - 

! @75kb1hpim - Internal server error, for (POST) [/User/Schedule/Clear] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[PersistenceException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30066ms.]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:252)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:251)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.link(Promise.scala:337)
	at scala.concurrent.impl.Promise$DefaultPromise.linkRootOf(Promise.scala:322)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:39)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: javax.persistence.PersistenceException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30066ms.
	at io.ebeaninternal.server.transaction.TransactionFactoryBasic.create(TransactionFactoryBasic.java:45)
	at io.ebeaninternal.server.transaction.TransactionFactoryBasic.createQueryTransaction(TransactionFactoryBasic.java:25)
	at io.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:250)
	at io.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:2147)
	at io.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:215)
	at io.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1169)
	at io.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1062)
	at io.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1048)
	at io.ebean.Finder.byId(Finder.java:132)
	at models.Order.OrderSchedule.getOrderScheduleByUserId(OrderSchedule.java:55)
	at controllers.Order.ScheduleController.clearScheduleItems(ScheduleController.java:155)
	at controllers.Order.ScheduleController.clearSchedule(ScheduleController.java:143)
	at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$66(Routes.scala:1837)
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:139)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:110)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:78)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
	at play.filters.csrf.RequireCSRFCheckAction.call(RequireCSRFCheckAction.java:86)
	at annotations.CheckCSRF.call(CheckCSRF.java:20)
	at annotations.SessionVerifier.RequiresActive.call(RequiresActive.java:42)
	at play.core.j.JavaAction.$anonfun$apply$2(JavaAction.scala:113)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
	at scala.concurrent.impl.Promise.transform(Promise.scala:29)
	at scala.concurrent.impl.Promise.transform$(Promise.scala:27)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:375)
	at scala.concurrent.Future.map(Future.scala:287)
	at scala.concurrent.Future.map$(Future.scala:287)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:375)
	at scala.concurrent.Future$.apply(Future.scala:653)
	at play.core.j.JavaAction.apply(JavaAction.scala:113)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	... 12 common frames omitted
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30066ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:601)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
	at org.jdbcdslog.DataSourceProxyBase.getConnection(DataSourceProxyBase.java:45)
	at play.db.ebean.DefaultEbeanConfig$EbeanConfigParser$WrappingDatasource.getConnection(DefaultEbeanConfig.java:154)
	at io.ebeaninternal.server.transaction.TransactionFactoryBasic.create(TransactionFactoryBasic.java:37)
	... 57 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1187)
	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1182)
	at com.mysql.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:5506)
	at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:530)
	at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:169)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:170)
	... 62 common frames omitted
>>>>>>> Customer-Management-Dev
